// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjn9r4Tp6Yy3DNkm8dCrWEDxnTEVayGK0',
    appId: '1:1060813024577:web:f3b40f45d8afa1ebdf85c0',
    messagingSenderId: '1060813024577',
    projectId: 'faris-projects',
    authDomain: 'faris-projects.firebaseapp.com',
    databaseURL: 'https://faris-projects-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faris-projects.appspot.com',
    measurementId: 'G-8V0FD4H6MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9LcI8Y8PHOfdW2NX5Fe9KhguB58ES2m0',
    appId: '1:1060813024577:android:f55a3d04a550e8bbdf85c0',
    messagingSenderId: '1060813024577',
    projectId: 'faris-projects',
    databaseURL: 'https://faris-projects-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faris-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOVRLnhryhr_P0ZGNDUNhXtmRp_4DBQs',
    appId: '1:1060813024577:ios:4322027c60ab106fdf85c0',
    messagingSenderId: '1060813024577',
    projectId: 'faris-projects',
    databaseURL: 'https://faris-projects-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faris-projects.appspot.com',
    iosBundleId: 'com.example.farisFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOVRLnhryhr_P0ZGNDUNhXtmRp_4DBQs',
    appId: '1:1060813024577:ios:4322027c60ab106fdf85c0',
    messagingSenderId: '1060813024577',
    projectId: 'faris-projects',
    databaseURL: 'https://faris-projects-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faris-projects.appspot.com',
    iosBundleId: 'com.example.farisFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjn9r4Tp6Yy3DNkm8dCrWEDxnTEVayGK0',
    appId: '1:1060813024577:web:49ece77528816f53df85c0',
    messagingSenderId: '1060813024577',
    projectId: 'faris-projects',
    authDomain: 'faris-projects.firebaseapp.com',
    databaseURL: 'https://faris-projects-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faris-projects.appspot.com',
    measurementId: 'G-N78NVQSKBC',
  );
}
